### ISSUE TITLE
2.1.3版提示找不到douyu文件夹和douyudm的module

### ISSUE THREAD

**Issue by TennoClash** [Tilerphy/ps4broadcast#47]
[root@localhost ps4broadcast]# ./start-web.sh ens33
mkdir: cannot create directory ‘node_modules’: File exists
cp: cannot stat ‘./douyu/*’: No such file or directory
net.ipv4.ip_forward = 1
_realroll.js is loaded.
room_bilibili.js is loaded as room module.
room_douyu.js is loaded as room module.
module.js:550
    throw err;
    ^

Error: Cannot find module 'douyudm'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/ps4broadcast/modules/room_douyu.js:3:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

上个版本都有douyuu这个文件夹，少东西了？

**Comment by Tilerphy** [comment]
等我看看啊，这几天更新了新的东西，稍等



在 2020-07-22 16:37:41，"WD" <notifications@github.com> 写道：

[root@localhost ps4broadcast]# sudo ./start-web.sh ens33
mkdir: cannot create directory ‘node_modules’: File exists
cp: cannot stat ‘./douyu/*’: No such file or directory
net.ipv4.ip_forward = 1
_realroll.js is loaded.
room_bilibili.js is loaded as room module.
room_douyu.js is loaded as room module.
module.js:550
throw err;
^

Error: Cannot find module 'douyudm'
at Function.Module._resolveFilename (module.js:548:15)
at Function.Module._load (module.js:475:25)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object. (/root/ps4broadcast/modules/room_douyu.js:3:13)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)

上个版本都有douyuu这个文件夹，少东西了？

**Comment by Tilerphy** [comment]
已经修复，非常抱歉。



在 2020-07-22 16:37:41，"WD" <notifications@github.com> 写道：

[root@localhost ps4broadcast]# sudo ./start-web.sh ens33
mkdir: cannot create directory ‘node_modules’: File exists
cp: cannot stat ‘./douyu/*’: No such file or directory
net.ipv4.ip_forward = 1
_realroll.js is loaded.
room_bilibili.js is loaded as room module.
room_douyu.js is loaded as room module.
module.js:550
throw err;
^

Error: Cannot find module 'douyudm'
at Function.Module._resolveFilename (module.js:548:15)
at Function.Module._load (module.js:475:25)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object. (/root/ps4broadcast/modules/room_douyu.js:3:13)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)

上个版本都有douyuu这个文件夹，少东西了？

**Comment by Tilerphy** [comment]
更新后忘记了提交新增文件夹，已经进行了修复，造成不便非常抱歉。

**Comment by Tilerphy** [comment]
点击更新后记可拉去确实的文件。
