### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by Asiimoviet** [Tilerphy/ps4broadcast#58]
环境：Linux Zephyrus-G15 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux

由于无法按照作者你readme中的步骤安装nodejs（一直在打印一堆信息打印了好几分钟我就ctrl+c停掉了），我使用了apt-get install nodejs npm来安装，得到的nodejs的版本是v12.22.5，然后npm的版本是7.5.2。运行了start-web.sh以后出现了这个：
``` bash
asiimoviet@Zephyrus-G15:~/ps4broadcast$ sudo ./start-web.sh eth0
net.ipv4.ip_forward = 1
_realroll.js is loaded.
_realroll.js:Zone.Identifier is loaded.
/home/asiimoviet/ps4broadcast/modules/_realroll.js:Zone.Identifier:3
ReferrerUrl=https://github.com/Tilerphy/ps4broadcast
                 ^

SyntaxError: Unexpected token ':'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/asiimoviet/ps4broadcast/start.js:22:43)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

我使用了wsl2的bridge桥接模式把这个debian接入了和PS5同一个网络下的路由器：
``` bash
asiimoviet@Zephyrus-G15:~/ps4broadcast$ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.50.50  netmask 255.255.255.0  broadcast 192.168.50.255
        ether 00:15:5d:f1:8c:be  txqueuelen 1000  (Ethernet)
        RX packets 46271  bytes 60015198 (57.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12887  bytes 860802 (840.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0:2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.200.1  netmask 255.255.255.0  broadcast 192.168.200.255
        ether 00:15:5d:f1:8c:be  txqueuelen 1000  (Ethernet)

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 16  bytes 1104 (1.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 16  bytes 1104 (1.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
![image](https://user-images.githubusercontent.com/66727875/157933646-2d3c90ee-f7bb-4aa4-845d-81737f431001.png)

第一个是PS5 第二个是主机 第三个是WSL

作者可以看看可能是什么样的问题吗

**Comment by Asiimoviet** [comment]
这个问题已经解决了，那个zone identifier是系统自己加的，把那些文件删掉就好了。
