### ISSUE TITLE
求指导：start-web 报错 

### ISSUE THREAD

**Issue by shui9527** [Tilerphy/ps4broadcast#72]
root@shui-virtual-machine:/ps4broadcast/ps4broadcast# sudo ./start-web.sh ens33
net.ipv4.ip_forward = 1
_realroll.js is loaded.
room_bilibili.js is loaded as room module.
room_douyu.js is loaded as room module.
{ Error: getaddrinfo EAI_AGAIN api.bilibili.com:443
    at Object._errnoException (util.js:1021:11)
    at errnoException (dns.js:58:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'api.bilibili.com',
  host: 'api.bilibili.com',
  port: 443 }
{ Error: socket hang up
    at createHangUpError (_http_client.js:329:15)
    at TLSSocket.socketCloseListener (_http_client.js:361:23)
    at emitOne (events.js:120:20)
    at TLSSocket.emit (events.js:210:7)
    at _handle.close (net.js:547:12)
    at TCP.done [as _onclose] (_tls_wrap.js:356:7) code: 'ECONNRESET' }

是因为b站的api更新的原因吗？

**Comment by Tilerphy** [comment]
对，暂时不更新b站弹幕回传了，b站的api隐蔽且不稳定。对开发者极其不友好



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月07日 10:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [Tilerphy/ps4broadcast] 求指导：start-web 报错  (Issue #72) |

***@***.***:/ps4broadcast/ps4broadcast# sudo ./start-web.sh ens33
net.ipv4.ip_forward = 1
_realroll.js is loaded.
room_bilibili.js is loaded as room module.
room_douyu.js is loaded as room module.
{ Error: getaddrinfo EAI_AGAIN api.bilibili.com:443
at Object._errnoException (util.js:1021:11)
at errnoException (dns.js:58:15)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)
code: 'EAI_AGAIN',
errno: 'EAI_AGAIN',
syscall: 'getaddrinfo',
hostname: 'api.bilibili.com',
host: 'api.bilibili.com',
port: 443 }
{ Error: socket hang up
at createHangUpError (_http_client.js:329:15)
at TLSSocket.socketCloseListener (_http_client.js:361:23)
at emitOne (events.js:120:20)
at TLSSocket.emit (events.js:210:7)
at _handle.close (net.js:547:12)
at TCP.done [as _onclose] (_tls_wrap.js:356:7) code: 'ECONNRESET' }

是因为b站的api更新的原因吗？
